/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        card: 'var(--card)',
        'card-foreground': 'var(--card-foreground)',
        popover: 'var(--popover)',
        'popover-foreground': 'var(--popover-foreground)',
        primary: 'var(--primary)',
        'primary-foreground': 'var(--primary-foreground)',
        secondary: 'var(--secondary)',
        'secondary-foreground': 'var(--secondary-foreground)',
        muted: 'var(--muted)',
        'muted-foreground': 'var(--muted-foreground)',
        accent: 'var(--accent)',
        'accent-foreground': 'var(--accent-foreground)',
        destructive: 'var(--destructive)',
        border: 'var(--border)',
        input: 'var(--input)',
        ring: 'var(--ring)',
        'chart-1': 'var(--chart-1)',
        'chart-2': 'var(--chart-2)',
        'chart-3': 'var(--chart-3)',
        'chart-4': 'var(--chart-4)',
        'chart-5': 'var(--chart-5)',
        sidebar: 'var(--sidebar)',
        'sidebar-foreground': 'var(--sidebar-foreground)',
        'sidebar-primary': 'var(--sidebar-primary)',
        'sidebar-primary-foreground': 'var(--sidebar-primary-foreground)',
        'sidebar-accent': 'var(--sidebar-accent)',
        'sidebar-accent-foreground': 'var(--sidebar-accent-foreground)',
        'sidebar-border': 'var(--sidebar-border)',
        'sidebar-ring': 'var(--sidebar-ring)',
        'bg-primary': 'var(--bg-primary)',
        'bg-secondary': 'var(--bg-secondary)',
        'bg-card': 'var(--bg-card)',
        'bg-card-hover': 'var(--bg-card-hover)',
        'bg-input': 'var(--bg-input)',
        'bg-elevated': 'var(--bg-elevated)',
        gold: 'rgb(var(--gold-rgb) / <alpha-value>)',
        'gold-light': 'var(--gold-light)',
        'gold-dark': 'var(--gold-dark)',
        'gold-bg': 'var(--gold-bg)',
        'gold-border': 'var(--gold-border)',
        success: 'rgb(var(--success-rgb) / <alpha-value>)',
        'success-bg': 'var(--success-bg)',
        danger: 'rgb(var(--danger-rgb) / <alpha-value>)',
        'danger-bg': 'var(--danger-bg)',
        warning: 'rgb(var(--warning-rgb) / <alpha-value>)',
        'warning-bg': 'var(--warning-bg)',
        info: 'rgb(var(--info-rgb) / <alpha-value>)',
        'info-bg': 'var(--info-bg)',
        'text-primary': 'var(--text-primary)',
        'text-secondary': 'var(--text-secondary)',
        'text-muted': 'var(--text-muted)',
        'text-gold': 'var(--text-gold)',
        'border-strong': 'var(--border-strong)',
        'border-gold': 'var(--border-gold)',
        // TrackOps specific colors
        'trackops-bg': '#050505',
        'trackops-navy': '#0A1128',
        'trackops-steel': '#1E293B',
        'trackops-green': '#00FF66',
        'trackops-red': '#FF2A2A',
        'trackops-amber': '#FFB000',
        'trackops-border': '#1E293B',
        'trackops-card': '#0B1221',
        // Trackify Labs specific colors
        'labs-bg': '#09090b',
        'labs-card': '#121214',
        'labs-border': '#27272a',
        'labs-cyan': '#22d3ee',
        'labs-purple': '#c084fc',
        'labs-accent': '#0ea5e9',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        heading: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      animation: {
        'radar-spin': 'radar-spin 4s linear infinite',
        'pulse-glow': 'pulse-glow 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
      keyframes: {
        'radar-spin': {
          '0%': { transform: 'rotate(0deg)' },
          '100%': { transform: 'rotate(360deg)' },
        },
        'pulse-glow': {
          '0%, 100%': { opacity: 1, boxShadow: '0 0 15px rgba(0, 255, 102, 0.5)' },
          '50%': { opacity: .7, boxShadow: '0 0 5px rgba(0, 255, 102, 0.2)' },
        },
      },
    },
  },
  plugins: [],
}