import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

import '../../providers/language_provider.dart';

class AppText {
  static const Map<String, Map<String, String>> _translations = {
    'en': {
      'supervisorDashboard': 'Supervisor Dashboard',
      'labourManagement': 'Labour Management',
      'attendance': 'Attendance',
      'reports': 'Reports',
      'dashboard': 'Dashboard',
      'labour': 'Labour',
      'logout': 'Logout',
      'cancel': 'Cancel',
      'logoutConfirm': 'Are you sure you want to logout?',
      'language': 'Language',
      'english': 'English',
      'hindi': 'Hindi',
      'gujarati': 'Gujarati',
      'labourMode': 'Labour Mode',
      'callSupervisor': 'Call Supervisor',
      'supervisorUnavailable': 'Supervisor number is not available.',
      'selectYourName': 'Select your name',
        'labourLoginTitle': 'Labour Login',
        'labourLoginSubtitle': 'Login with your registered mobile number.',
        'mobileNumber': 'Mobile Number',
        'mobileNumberHint': 'Enter 10-digit number',
        'mobileRequired': 'Please enter your mobile number',
        'mobileInvalid': 'Please enter a valid 10-digit mobile number',
        'mobileNotFound': 'Mobile number not found. Please contact supervisor.',
      'viewReadOnly': 'View your work and attendance details (read-only).',
      'noLabourFound':
          'No labour found. Please add labour from Supervisor Mode.',
      'labourName': 'Labour Name',
        'login': 'Login',
      'continue': 'Continue',
      'totalDaysWorked': 'Total Days Worked',
      'dailyWage': 'Daily Wage',
      'totalEarned': 'Total Earned',
      'basePay': 'Base Pay',
      'basePlusOvertime': 'Base Pay + Overtime',
      'extraHours': 'Extra Hours',
      'overtimeRate': 'Overtime Rate',
      'overtimePay': 'Overtime Pay',
      'advanceTaken': 'Advance Taken',
      'finalPay': 'Final Pay',
      'finalPayFormula': 'Final Pay = Base Pay + Overtime - Advance',
      'workdays': 'Workdays',
      'advance': 'Advance',
      'present': 'Present',
      'half': 'Half',
      'absent': 'Absent',
      'noReportData': 'No report data yet',
    },
    'hi': {
      'supervisorDashboard': 'सुपरवाइजर डैशबोर्ड',
      'labourManagement': 'मजदूर प्रबंधन',
      'attendance': 'उपस्थिति',
      'reports': 'रिपोर्ट',
      'dashboard': 'डैशबोर्ड',
      'labour': 'मजदूर',
      'logout': 'लॉगआउट',
      'cancel': 'रद्द करें',
      'logoutConfirm': 'क्या आप वाकई लॉगआउट करना चाहते हैं?',
      'language': 'भाषा',
      'english': 'अंग्रेज़ी',
      'hindi': 'हिंदी',
      'gujarati': 'गुजराती',
      'labourMode': 'मजदूर मोड',
      'callSupervisor': 'सुपरवाइजर को कॉल करें',
      'supervisorUnavailable': 'सुपरवाइजर का नंबर उपलब्ध नहीं है।',
      'selectYourName': 'अपना नाम चुनें',
        'labourLoginTitle': 'मजदूर लॉगिन',
        'labourLoginSubtitle': 'अपने पंजीकृत मोबाइल नंबर से लॉगिन करें।',
        'mobileNumber': 'मोबाइल नंबर',
        'mobileNumberHint': '10 अंकों का नंबर दर्ज करें',
        'mobileRequired': 'कृपया मोबाइल नंबर दर्ज करें',
        'mobileInvalid': 'कृपया सही 10 अंकों का मोबाइल नंबर दर्ज करें',
        'mobileNotFound':
          'मोबाइल नंबर नहीं मिला। कृपया सुपरवाइजर से संपर्क करें।',
      'viewReadOnly':
          'अपने काम और उपस्थिति का विवरण देखें (केवल पढ़ने के लिए)।',
      'noLabourFound':
          'कोई मजदूर नहीं मिला। कृपया सुपरवाइजर मोड से मजदूर जोड़ें।',
      'labourName': 'मजदूर का नाम',
        'login': 'लॉगिन',
      'continue': 'जारी रखें',
      'totalDaysWorked': 'कुल दिन',
      'dailyWage': 'दैनिक मजदूरी',
      'totalEarned': 'कुल कमाई',
      'basePay': 'मूल भुगतान',
      'basePlusOvertime': 'मूल भुगतान + ओवरटाइम',
      'extraHours': 'अतिरिक्त घंटे',
      'overtimeRate': 'ओवरटाइम दर',
      'overtimePay': 'ओवरटाइम भुगतान',
      'advanceTaken': 'अग्रिम राशि',
      'finalPay': 'अंतिम भुगतान',
      'finalPayFormula': 'अंतिम भुगतान = मूल भुगतान + ओवरटाइम - अग्रिम',
      'workdays': 'कार्य दिवस',
      'advance': 'अग्रिम',
      'present': 'उपस्थित',
      'half': 'आधा',
      'absent': 'अनुपस्थित',
      'noReportData': 'अभी रिपोर्ट डेटा नहीं है',
    },
    'gu': {
      'supervisorDashboard': 'સુપરવાઇઝર ડેશબોર્ડ',
      'labourManagement': 'મજૂર વ્યવસ્થાપન',
      'attendance': 'હાજરી',
      'reports': 'રિપોર્ટ્સ',
      'dashboard': 'ડેશબોર્ડ',
      'labour': 'મજૂર',
      'logout': 'લોગઆઉટ',
      'cancel': 'રદ કરો',
      'logoutConfirm': 'શું તમે ખરેખર લોગઆઉટ કરવા માંગો છો?',
      'language': 'ભાષા',
      'english': 'અંગ્રેજી',
      'hindi': 'હિન્દી',
      'gujarati': 'ગુજરાતી',
      'labourMode': 'મજૂર મોડ',
      'callSupervisor': 'સુપરવાઇઝરને કોલ કરો',
      'supervisorUnavailable': 'સુપરવાઇઝરનો નંબર ઉપલબ્ધ નથી.',
      'selectYourName': 'તમારું નામ પસંદ કરો',
        'labourLoginTitle': 'મજૂર લોગિન',
        'labourLoginSubtitle': 'તમારા નોંધાયેલા મોબાઇલ નંબરથી લોગિન કરો.',
        'mobileNumber': 'મોબાઇલ નંબર',
        'mobileNumberHint': '10 અંકનો નંબર દાખલ કરો',
        'mobileRequired': 'કૃપા કરીને મોબાઇલ નંબર દાખલ કરો',
        'mobileInvalid': 'કૃપા કરીને માન્ય 10 અંકનો મોબાઇલ નંબર દાખલ કરો',
        'mobileNotFound':
          'મોબાઇલ નંબર મળ્યો નથી. કૃપા કરીને સુપરવાઇઝરનો સંપર્ક કરો.',
      'viewReadOnly': 'તમારું કામ અને હાજરી વિગત જુઓ (ફક્ત વાંચવા માટે).',
      'noLabourFound':
          'કોઈ મજૂર મળ્યો નથી. કૃપા કરીને સુપરવાઇઝર મોડમાં મજૂર ઉમેરો.',
      'labourName': 'મજૂરનું નામ',
        'login': 'લોગિન',
      'continue': 'આગળ વધો',
      'totalDaysWorked': 'કુલ દિવસ',
      'dailyWage': 'દૈનિક વેતન',
      'totalEarned': 'કુલ કમાણી',
      'basePay': 'મૂળ ચુકવણી',
      'basePlusOvertime': 'મૂળ ચુકવણી + ઓવરટાઈમ',
      'extraHours': 'વધારાના કલાકો',
      'overtimeRate': 'ઓવરટાઈમ દર',
      'overtimePay': 'ઓવરટાઈમ ચુકવણી',
      'advanceTaken': 'એડવાન્સ રકમ',
      'finalPay': 'અંતિમ ચુકવણી',
      'finalPayFormula': 'અંતિમ ચુકવણી = મૂળ ચુકવણી + ઓવરટાઈમ - એડવાન્સ',
      'workdays': 'કાર્ય દિવસ',
      'advance': 'એડવાન્સ',
      'present': 'હાજર',
      'half': 'અડધો',
      'absent': 'ગેરહાજર',
      'noReportData': 'હજુ સુધી રિપોર્ટ ડેટા નથી',
    },
  };

  static String tr(BuildContext context, String key) {
    final provider = context.watch<LanguageProvider>();
    final code = provider.locale.languageCode;
    return _translations[code]?[key] ?? _translations['en']?[key] ?? key;
  }
}

extension AppTextX on BuildContext {
  String tr(String key) => AppText.tr(this, key);
}
